### ISSUE TITLE
📦 Unnecessary dependency on Mypy

### ISSUE THREAD

**Issue by connorbrinton** [rspeer/wordfreq#100]
[This commit introduced](https://github.com/rspeer/wordfreq/commit/342c1d0f0ef03dfff95f962c4da8a89290dbf213) Mypy as a `wordfreq` dependency, but there doesn't appear to be any runtime functionality provided by this dependency. I use a newer version of Mypy in one of my projects, which causes the following error when I try to install `wordfreq`:
```
Because wordfreq (3.0.0) depends on mypy (>=0.931,<0.932)
   and no versions of wordfreq match >3.0.0,<4.0.0, wordfreq (>=3.0.0,<4.0.0) requires mypy (>=0.931,<0.932).
  So, because my-project depends on both mypy (0.941) and wordfreq (^3.0.0), version solving failed.
```

Since there's no need to include Mypy as a main dependency, could it be moved to the dev dependencies for this project?

In the meantime, I'm using an earlier release of this project (2.5.1), which doesn't have the dependency on Mypy

Thanks for maintaining wordfreq! 😄

**Comment by rspeer** [comment]
Fixed in 3.0.1. Thanks!
