### ISSUE TITLE
newest version does not work?

### ISSUE THREAD

**Issue by JINHXu** [rspeer/wordfreq#104]
Hey there,

after pip installing the newest version, I constantly get this error:

```
>>> from wordfreq import word_frequency
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xujinghua/miniconda3/lib/python3.7/site-packages/wordfreq/__init__.py", line 16, in <module>
    from .numbers import digit_freq, has_digit_sequence, smash_numbers
  File "/Users/xujinghua/miniconda3/lib/python3.7/site-packages/wordfreq/numbers.py", line 99, in <module>
    def _sub_zeroes(match: regex.Match) -> str:
AttributeError: module 'regex' has no attribute 'Match'
```

whereas `wordfreq 1.4` works fine. Does anyone know how to fix this? Thanks a lot for your help in advance!

Cheers,
Xu

**Comment by rspeer** [comment]
This may be because of the lack of semantic versioning on the `regex` library. Can you look in your dependencies and tell me which version of regex you have?

**Comment by rspeer** [comment]
oh, I found it. Versions from 2020.4.4 to 2021.4.4 are lacking the regex.Match type. I set a new minimum version.

**Comment by JINHXu** [comment]
Hi Elia! Thanks for your help! It works now :)
