### ISSUE TITLE
Mix-up between Slovenian and Slovak in README.md

### ISSUE THREAD

**Issue by tderflinger** [rspeer/wordfreq#108]
Hi!

Thanks for this great application! I just wanted to tell you that the ISO 639-1 code for Slovenian is `sl` and the code for Slovak is `sk`.
I think you got that mixed-up in the table in your README.md.
Yes, the two countries have very similar flags, names, and languages :)

Best regards

**Comment by rspeer** [comment]
Sorry about that, fixed!
